gui:
  showIcons: true
  showCommandLog: true
  commandLogSize: 8
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - "#303030"
    optionsTextColor:
      - "#e78a4e"
os:
  open: "cursor -rg {{filename}}"
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
