[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "ll"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "lf"

[[session]]
name = "Dotfiles ğŸ”§"
path = "~/workspace/dotfiles"

[[session]]
name = "Sencrop app"
path = "~/workspace/sencrop/sencrop-app"
script_path = "~/.config/sesh/scripts/sencrop/start-app"
